import "./globals.css";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  // console.log(session, "session");

  return (
    <html lang='en'>
      <body>
        <div className='navbar'>
          <Link href='/' className='logo'>
            Forum
          </Link>
          <Link href='/list'>List</Link>
          <Link href='/register'>가입</Link>
          <LoginBtn session={session} />
          {session && (
            <span style={{ float: "right", lineHeight: "2rem" }}>
              Welcome {session.user.name}
            </span>
          )}
        </div>
        {children}
      </body>
    </html>
  );
}
